# Generated by Django 4.1.7 on 2023-02-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cats',
            options={'verbose_name': 'Коты', 'verbose_name_plural': 'Коты'},
        ),
        migrations.AlterModelOptions(
            name='dogs',
            options={'verbose_name': 'Собаки', 'verbose_name_plural': 'Собаки'},
        ),
        migrations.AlterField(
            model_name='cats',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='homecountry',
            field=models.CharField(max_length=255, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='cats',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='homecountry',
            field=models.CharField(max_length=255, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='фото'),
        ),
    ]
